version: '3.8'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - dashboardx_network
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
      - smtp4dev
  postgres:
    image: postgres:15
    restart: always
    networks:
      - dashboardx_network
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass secret_password
    networks:
      - dashboardx_network
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - '5000:80'
      - '587:587'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__Port=587
      - ServerOptions__TlsMode=ImplicitTls
    networks:
      - dashboardx_network
networks:
  dashboardx_network:
    name: 'dev-network'
    ipam:
      config:
        - subnet: 192.168.192.1/24
volumes:
  smtp4dev-data:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local